name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-test-env
      - id: npm-publish
        name: Publish wds to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
      - name: Publish Release to github
        uses: softprops/action-gh-release@v1
        if: ${{ steps.npm-publish.outputs.type != 'none' }}
        with:
          tag_name: ${{ steps.npm-publish.outputs.version }}
          generate_release_notes: true